---
- name: Configure Raspberry Pi WiFi hotspot
  hosts: raspberrypi
  become: yes
  tasks:

    # Ensure required packages are installed
    - name: Install dnsmasq
      apt:
        name: dnsmasq
        state: present

    # Install hostapd if not already installed
    - name: Install hostapd
      apt:
        name: hostapd
        state: present

    # Configure hostapd for wlan1
    - name: Configure hostapd
      copy:
        dest: /etc/hostapd/hostapd.conf
        content: |
          interface=wlan1
          driver=nl80211
          ssid=RaspberryPi-Hotspot
          hw_mode=g
          channel=7
          wmm_enabled=0
          macaddr_acl=0
          auth_algs=1
          ignore_broadcast_ssid=0
          wpa=2
          wpa_passphrase=YourSecurePassword
          wpa_key_mgmt=WPA-PSK
          rsn_pairwise=CCMP
      notify: restart hostapd

    # Configure systemd-networkd for wlan1 static IP
    - name: Configure systemd-networkd for wlan1 static IP
      copy:
        dest: /etc/systemd/network/30-wlan1.network
        content: |
          [Match]
          Name=wlan1

          [Network]
          Address=192.168.50.1/24
          # Disable DHCPServer here
          # DHCPServer=yes

    # Install and configure dnsmasq
    - name: Configure dnsmasq for DHCP on wlan1
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          interface=wlan1
          dhcp-range=192.168.50.10,192.168.50.100,12h
          dhcp-option=3,192.168.50.1  # Gateway
          dhcp-option=6,192.168.50.1  # DNS

    # Enable and start dnsmasq
    - name: Enable and start dnsmasq
      systemd:
        name: dnsmasq
        enabled: yes
        state: started

    # Disable systemd-networkd DHCP server
    - name: Disable systemd-networkd DHCP server
      lineinfile:
        path: /etc/systemd/network/30-wlan1.network
        regexp: '^DHCPServer='
        line: '#DHCPServer=yes'

    # Restart systemd-networkd to apply changes
    - name: Restart systemd-networkd
      systemd:
        name: systemd-networkd
        state: restarted

    # Ensure hostapd starts
    - name: Start hostapd service
      systemd:
        name: hostapd
        enabled: yes
        state: started

  handlers:
    # Restart hostapd after configuration change
    - name: restart hostapd
      systemd:
        name: hostapd
        state: restarted

