---
- name: Setup Raspberry Pi Wi-Fi Hotspot
  hosts: localhost
  become: yes

  tasks:

    - name: Install required packages
      apt:
        name:
          - hostapd
          - dnsmasq
          - iptables
          - network-manager
        state: present
        update_cache: yes

    - name: Ensure hostapd is unmasked and enabled
      command: systemctl unmask hostapd
      notify: Restart hostapd

    - name: Enable and start hostapd
      systemd:
        name: hostapd
        enabled: yes
        state: started

    - name: Configure wlan1 IP with NetworkManager
      copy:
        dest: /etc/NetworkManager/system-connections/wlan1.nmconnection
        content: |
          [connection]
          id=wlan1
          type=wifi
          interface-name=wlan1
          autoconnect=true

          [ipv4]
          method=manual
          addresses=192.168.50.1/24
      notify: Restart NetworkManager

    - name: Restart NetworkManager to apply settings
      systemd:
        name: NetworkManager
        state: restarted

    - name: Set up NAT for internet sharing
      shell: |
        iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE
      notify: Save iptables rules

    - name: Ensure IP forwarding is enabled
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present

  handlers:
    - name: Restart hostapd
      systemd:
        name: hostapd
        state: restarted

    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted

    - name: Save iptables rules
      shell: iptables-save > /etc/iptables/rules.v4

