---
- name: Setup Raspberry Pi as AP with dnsmasq
  hosts: localhost
  become: yes
  tasks:
    - name: Stop and disable systemd-resolved to free port 53
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no

    - name: Install dnsmasq
      apt:
        name: dnsmasq
        state: present

    - name: Configure dnsmasq for DHCP
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          interface=wlan1
          dhcp-range=192.168.50.10,192.168.50.100,12h
          dhcp-option=3,192.168.50.1
          dhcp-option=6,192.168.50.1
          domain-needed
          bogus-priv
          no-resolv
          local=/local/
          server=8.8.8.8
          server=8.8.4.4

    - name: Restart dnsmasq to apply changes
      systemd:
        name: dnsmasq
        state: restarted

    - name: Enable dnsmasq to start at boot
      systemd:
        name: dnsmasq
        enabled: yes

    - name: Start hostapd
      systemd:
        name: hostapd
        state: started
        enabled: yes

    - name: Restart networkd to apply network settings
      systemd:
        name: systemd-networkd
        state: restarted

    - name: Ensure wlan1 is configured correctly
      shell: |
        ip addr show wlan1
        ip link set wlan1 up
        ip addr add 192.168.50.1/24 dev wlan1
        systemctl restart systemd-networkd

