---
- name: Set up Wi-Fi hotspot on Raspberry Pi
  hosts: raspberrypi
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - dnsmasq
          - hostapd
          - iptables
          - iptables-persistent
        state: present
        update_cache: yes

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    - name: Set up iptables for NAT (internet sharing from wlan0 to wlan1)
      command: iptables -t nat -A POSTROUTING -o wlan0 -j MASQUERADE

    - name: Allow traffic forwarding from wlan1 to wlan0
      command: iptables -A FORWARD -i wlan1 -o wlan0 -j ACCEPT

    - name: Save iptables rules
      shell: iptables-save > /etc/iptables/rules.v4

    - name: Configure dnsmasq for DHCP
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          interface=wlan1
          dhcp-range=192.168.50.10,192.168.50.50,12h
          dhcp-option=3,192.168.50.1
          dhcp-option=6,8.8.8.8
          address=/test/192.168.50.1

    - name: Enable and start dnsmasq
      systemd:
        name: dnsmasq
        enabled: yes
        state: started

    - name: Configure hostapd for access point
      copy:
        dest: /etc/hostapd/hostapd.conf
        content: |
          interface=wlan1
          driver=nl80211
          ssid=Pi_Hotspot
          hw_mode=g
          channel=7
          macaddr_acl=0
          auth_algs=1
          wpa=2
          wpa_passphrase=raspberry
          wpa_key_mgmt=WPA-PSK
          ieee80211n=1
          country=US

    - name: Configure hostapd default config
      copy:
        dest: /etc/default/hostapd
        content: |
          DAEMON_CONF="/etc/hostapd/hostapd.conf"

    - name: Enable and start hostapd
      systemd:
        name: hostapd
        enabled: yes
        state: started

    - name: Configure systemd-networkd for wlan1 (hotspot)
      copy:
        dest: /etc/systemd/network/10-wlan1.network
        content: |
          [Match]
          Name=wlan1

          [Network]
          Address=192.168.50.1/24
          DHCPServer=yes

    - name: Configure systemd-networkd for wlan0 (home Wi-Fi)
      copy:
        dest: /etc/systemd/network/10-wlan0.network
        content: |
          [Match]
          Name=wlan0

          [Network]
          DHCP=ipv4

    - name: Restart systemd-networkd to apply changes
      systemd:
        name: systemd-networkd
        state: restarted

