---
- name: Set up Wi-Fi hotspot on Raspberry Pi
  hosts: localhost
  become: yes
  tasks:
    - name: Install necessary packages
      apt:
        name:
          - dnsmasq
          - hostapd
          - iptables
          - iptables-persistent
          - network-manager
        state: present
        update_cache: yes

    - name: Prevent NetworkManager from managing wlan1
      copy:
        dest: /etc/NetworkManager/conf.d/unmanaged-wlan1.conf
        content: |
          [keyfile]
          unmanaged-devices=interface-name:wlan1

    - name: Restart NetworkManager
      systemd:
        name: NetworkManager
        state: restarted

    - name: Enable IP forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: "1"
        state: present
        reload: yes

    - name: Set up iptables for NAT (internet sharing from wlan0 to wlan1)
      iptables:
        table: nat
        chain: POSTROUTING
        jump: MASQUERADE
        out_interface: wlan0

    - name: Allow traffic forwarding from wlan1 to wlan0
      iptables:
        chain: FORWARD
        in_interface: wlan1
        out_interface: wlan0
        jump: ACCEPT

    - name: Save iptables rules
      command: netfilter-persistent save

    - name: Configure dnsmasq for DHCP
      copy:
        dest: /etc/dnsmasq.conf
        content: |
          interface=wlan1
          dhcp-range=192.168.50.10,192.168.50.50,12h
          dhcp-option=3,192.168.50.1
          dhcp-option=6,8.8.8.8
          address=/test/192.168.50.1

    - name: Enable and start dnsmasq
      systemd:
        name: dnsmasq
        enabled: yes
        state: restarted

    - name: Configure hostapd for access point
      copy:
        dest: /etc/hostapd/hostapd.conf
        content: |
          interface=wlan1
          driver=nl80211
          ssid=Pi_Hotspot
          hw_mode=g
          channel=7
          macaddr_acl=0
          auth_algs=1
          wpa=2
          wpa_passphrase=raspberry
          wpa_key_mgmt=WPA-PSK
          ieee80211n=1
          country_code=US

    - name: Configure hostapd default config
      copy:
        dest: /etc/default/hostapd
        content: |
          DAEMON_CONF="/etc/hostapd/hostapd.conf"

    - name: Unmask and enable hostapd
      systemd:
        name: hostapd
        enabled: yes
        masked: no
        state: restarted

    - name: Configure systemd-networkd for wlan1 (hotspot)
      copy:
        dest: /etc/systemd/network/10-wlan1.network
        content: |
          [Match]
          Name=wlan1

          [Network]
          Address=192.168.50.1/24
          DHCPServer=yes

    - name: Restart systemd-networkd to apply changes
      systemd:
        name: systemd-networkd
        state: restarted

    - name: Bring up wlan1 manually
      command: ip link set wlan1 up

